docker-compose-yaml: docker-compose.yml

project: amazeeio-cdn

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    # Enable once config sync has been setup.
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli
    - run:
        name: Warm all the caches!
        command: drush xmlsitemap:rebuild && drush warmer:enqueue cdn,sitemap --run-queue
        service: cli

environments:
  master:
    routes:
      - nginx:
        - "cdn-demo.amazee.io":
            tls-acme: 'true'
            insecure: Redirect
    cronjobs:
      - name: drush cron
        schedule: "*/5 * * * *"
        command: drush cron
        service: cli
  9.x:
    # routes:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
